name: 'Release candidate'
description: 'create a release candidate branch and open a pull request from it a gainst the target branch'
inputs:
  target-branch:
    description: 'target branch'
    required: true
    default: master
  reviewers:
    description: 'release candidate PR reviewers'
    required: true
  api-key:
    description: 'linear personal api key'
    required: true
  GITHUB_TOKEN: 
    description: 'github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      name: configure git
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
    - name: Find Pull Request
      uses: juliangruber/find-pull-request-action@v1
      id: find-pull-request
      with:
        branch: release-candidate
    - name: Close Pull
      uses: peter-evans/close-pull@v2
      if: ${{ steps.find-pull-request.outputs.number > 0 }}
      with:
        pull-request-number: ${{ steps.find-pull-request.outputs.number }}
        comment: Redoing release candidate
        delete-branch: true
    - name: create release-candidate branch with rebasing
      shell: bash
      run: |
        git config --global push.default simple
        git checkout -b release-candidate
        git rebase origin/${{ inputs.target-branch }}
        git push --force-with-lease origin release-candidate 
    - name: create release-candidate branch without rebasing
      if: ${{ failure() }}
      shell: bash
      run: |
        git config --global push.default simple
        git checkout -b release-candidate
        git push origin release-candidate
    - name: pull-request-action
      id: cpr
      if: ${{ always() }}
      uses: vsoch/pull-request-action@1.0.12
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: ${{ inputs.target-branch }}
        PULL_REQUEST_REVIEWERS: ${{ inputs.reviewers }}
        PULL_REQUEST_TITLE:  "Release candidate" 
        PULL_REQUEST_FROM_BRANCH: "release-candidate"
        PULL_REQUEST_UPDATE: 'true'
    - name: Create comment on sprint review PR
      if: ${{ always() }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.cpr.outputs.pull_request_number }}
        body: |
          Welcome to the release candidate :tada:. 
          To see which issues are included in this release, 
          check the done column in your team's respective currently active cycle:
          - [Planner & Orders squad](https://linear.app/impargo/team/POS/cycle/active)
          - [DriverApp & Fleet squad](https://linear.app/impargo/team/DFS/cycle/active)
          - [DevOps squad](https://linear.app/impargo/team/DEV/cycle/active)
          - [Design squad](https://linear.app/impargo/team/DES/cycle/active)

        token: ${{ inputs.GITHUB_TOKEN }}